name: Build FNF-PeoteView

on:
  push:
    branches: [ official ]
  pull_request:
    branches: [ official ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.3.1 # Specify your Haxe version
    
    - name: Install Dependencies
      run: |
        haxelib git lime https://github.com/SomeGuyWhoLovesCoding/lime.git
        haxelib run lime rebuild tools
        haxelib run lime rebuild html5
        haxelib git peote-view https://github.com/maitag/peote-view.git
        haxelib install hxcpp
        haxelib install format
        haxelib git miniaudio https://github.com/alchemy-haxe/genkit_miniaudio.git
        haxelib install input2action
    
    - name: Build Project
      run: |
        haxelib run lime build html5 -release
