name: Build FNF-PeoteView

on:
  push:
    branches: [ official ]
  pull_request:
    branches: [ official ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.3.6 # Specify your Haxe version
    
    - name: Install Dependencies
      run: |
        haxelib install format --quiet
        haxelib git lime https://github.com/SomeGuyWhoLovesCoding/lime.git --quiet
        haxelib git peote-view https://github.com/maitag/peote-view.git --quiet
        haxelib install hxcpp --quiet
        haxelib install hxp --quiet
        haxelib git miniaudio https://github.com/alchemy-haxe/genkit_miniaudio.git --quiet
        haxelib install input2action --quiet
    
    - name: Build Project
      run: |
        haxelib run lime build html5 -release
