name: Build FNF-PeoteView

on:
  push:
    branches: [ official ]
  pull_request:
    branches: [ official ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install System Dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          g++ \
          g++-multilib \
          gcc-multilib \
          libasound2-dev \
          libx11-dev \
          libxext-dev \
          libxi-dev \
          libxrandr-dev \
          libxinerama-dev
    
    - name: Setup Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.3.6 # Specify your Haxe version
    
    - name: Install Dependencies
      run: |
        haxelib install format --quiet
        haxelib git lime https://github.com/SomeGuyWhoLovesCoding/lime.git --quiet
        haxelib git peote-view https://github.com/maitag/peote-view.git --quiet
        haxelib install hxcpp --quiet
        haxelib install hxp --quiet
        haxelib git miniaudio https://github.com/alchemy-haxe/genkit_miniaudio.git --quiet
        haxelib install input2action --quiet
    
    - name: Build Project
      run: |
        haxelib run lime build cpp
