# This is a basic workflow to help you get started with Actions

name: Build


# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ official ]
  pull_request:
    branches: [ official ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  WindowsBuild:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5.0.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6
      # Runs a set of commands using the runners shell
      - name: Install required haxelibs
        run: |
          haxelib setup C:/haxelib
          haxelib install format --quiet
          haxelib install hxp --quiet
          haxelib install hxcpp --quiet
          haxelib git lime https://github.com/SomeGuyWhoLovesCoding/lime.git --quiet
          haxelib install peote-view --quiet
          haxelib install input2action --quiet
          haxelib install customtitlebar --quiet
        shell: cmd
      - name: Check version tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: 'FV-Windows'
          path: bin/windows/bin
  LinuxBuild:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5.0.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6
      # Runs a set of commands using the runners shell
      - name: Install required Linux libraries
        run: |
          sudo apt-get install libc6-dev-i386
          export LIBRARY_PATH=/usr/lib/$(gcc -print-multiarch)
          export C_INCLUDE_PATH=/usr/include/$(gcc -print-multiarch)
          export CPLUS_INCLUDE_PATH=/usr/include/$(gcc -print-multiarch)
          sudo apt-get install g++-multilib
          sudo apt install libx11-dev
          sudo apt install libxrandr-dev
          sudo apt-get install libxinerama-dev
          sudo apt-get install libgl-dev
          sudo apt-get install libgl1-mesa-dev
          sudo apt-get install libglu1-mesa-dev
          sudo apt-get install libasound2-dev
          sudo apt-get install libdrm-dev

          # This shit is fucking important
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt-get install libgl-dev:i386
          sudo apt-get install libgl1-mesa-dev:i386
          sudo apt-get install libglu1-mesa-dev:i386
      - name: Install required haxelibs
        run: |
          haxelib setup ~/haxelib
          haxelib install format --quiet
          haxelib install hxp --quiet
          haxelib install hxcpp > /dev/null --quiet
          haxelib git lime https://github.com/SomeGuyWhoLovesCoding/lime.git --quiet
          haxelib install peote-view --quiet
          haxelib install input2action --quiet
          haxelib install customtitlebar --quiet
      - name: Check version tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
      # Zipping to tar.gz is important for extracting to an exe cuz normally if you zip it you will lose that permission
        run: |
          # Rebuild is required here, I'm on mobile
          haxelib run lime rebuild linux
          haxelib run lime build linux --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish artifact
        uses: nmerget/upload-gzip-artifact@main
        with:
          name: 'FV-Linux'
          path: bin/linux/bin
          retention-days: 5
